#!/bin/bash

PYTHON=python

PUSHMANAGER=$0
COMMAND=$1
MAIN_APP=pushmanager_main.py
API_APP=pushmanager_api.py
BASE_PATH=$(dirname $(readlink -f $0))

pushd $BASE_PATH > /dev/null


case "$COMMAND" in
    start|stop|restart)
		$PYTHON $API_APP $COMMAND && $PYTHON $MAIN_APP $COMMAND
		;;
    *)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac

popd > /dev/null

exit 0
